#!/bin/bash

################################################################################
### Error handling

# trap and abort-on Ctrl-c
control_c()
{
  echo "Build aborted"
  exit 1
}
trap control_c SIGINT

# exit of command fails
try()
{
  # run the command
  $@

  # save the exit code
  __exit_code__=$?

  # check the exit code
  if [ $__exit_code__ -ne 0 ] ; then
    exit $__exit_code__
  fi
}


# ensure that $DARK_CELL_ROOT is a valid directory
if [ ! -d "$DARK_CELL_ROOT" ] ; then echo "\$DARK_CELL_ROOT is not a valid directory" ; exit 1 ; fi


cd $DARK_CELL_ROOT
################################################################################
### Actual Script

# if the first argument is wipe, then wipe instead of building
if [ "$1" = "wipe" ] ; then
  rm -rf build
  rm -f execs/dcc
  exit 0
fi

mkdir -p build
cp -ruf src/* build
cp -u execs/Makefile build

cd build
try make $@

if [ -f "dcc" ] ; then
  cp -u dcc ../execs
fi

